name: l

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: dependcy
        run: |
          sudo apt update
          sudo apt install -y xvfb libgl1-mesa-dri mesa-utils curl

      - name: xsetup
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: renderfix
        run: |
          echo "LIBGL_ALWAYS_SOFTWARE=1" >> $GITHUB_ENV
          echo "GALLIUM_DRIVER=llvmpipe" >> $GITHUB_ENV

      - name: netsetup
        run: |
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
          sudo apt update
          sudo apt install -y tailscale

      - name: connect
        run: |
          sudo tailscale up --authkey "${{ secrets.TAILSCALE_AUTH_KEY }}" --accept-routes --advertise-exit-node --reset
          echo "✅ connected"
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: ipcheck
        run: |
          sleep 10
          ip=$(tailscale ip -4)
          echo ""
          echo "Address: $ip"
          echo ""
          echo "IP=$ip" >> $GITHUB_ENV

      - name: keep
        run: |
          echo "🟢 running..."
          while true; do
            sleep 300
            echo "💤 alive - $(date '+%H:%M:%S')"
          done